// @generated by protoc-gen-connect-es v0.8.6 with parameter "target=ts,import_extension=.ts"
// @generated from file counter.proto (package sst, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CountToRequest, CountToResponse } from "./counter_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service sst.CounterService
 */
export const CounterService = {
  typeName: "sst.CounterService",
  methods: {
    /**
     * Counts to a certain number, returning every integer in the process.
     *
     * @generated from rpc sst.CounterService.CountTo
     */
    countTo: {
      name: "CountTo",
      I: CountToRequest,
      O: CountToResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

