// @generated by protoc-gen-connect-query v0.2.0 with parameter "target=ts,import_extension=.ts"
// @generated from file counter.proto (package sst, syntax proto3)
/* eslint-disable */
// @ts-nocheck

export const typeName = "sst.CounterService";

